version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/AWS-PBL-Guestbook
     overwrite: true
permissions:
   - object: /var/www/html/AWS-PBL-Guestbook
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file
