version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/AWS-PBL-Guestbook
     overwrite: true
permissions:
   - object: /var/www/html/AWS-PBL-Guestbook
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
    BeforeInstall:
        - location: scripts/beforeinstall.bash
    AfterInstall:
        - location: scripts/afterinstall.bash